# Generated by Django 5.2.11 on 2026-03-03 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Continente')),
            ],
            options={
                'verbose_name': 'Continente',
                'verbose_name_plural': 'Continentes',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Gênero')),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('insta', models.CharField(max_length=100, verbose_name='Instagram')),
                ('nacionalidade', models.CharField(max_length=100, verbose_name='Nacionalidade')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='País')),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.continente', verbose_name='Continente')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('duracao', models.CharField(max_length=100, verbose_name='Duração')),
                ('sinopse', models.TextField(verbose_name='Sinopse')),
                ('data', models.DateField(verbose_name='Data de lançamento')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Nota de avaliação')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genero', verbose_name='Gênero')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais', verbose_name='País')),
                ('atores', models.ManyToManyField(blank=True, related_name='filmes_como_ator', to='app.pessoa', verbose_name='Atores')),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Diretor')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('duracao', models.CharField(max_length=100, verbose_name='Duração')),
                ('sinopse', models.TextField(verbose_name='Sinopse')),
                ('data', models.DateField(verbose_name='Data de lançamento')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Nota de avaliação')),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Diretor')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genero', verbose_name='Gênero')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número da temporada')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='app.serie', verbose_name='Série')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'unique_together': {('serie', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Título')),
                ('duracao', models.CharField(max_length=100, verbose_name='Duração')),
                ('data', models.DateField(verbose_name='Data de lançamento')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.temporada', verbose_name='Temporada')),
            ],
            options={
                'verbose_name': 'Episódio',
                'verbose_name_plural': 'Episódios',
            },
        ),
    ]
