# Generated by Django 5.2.11 on 2026-03-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='numero',
            field=models.IntegerField(default=1, verbose_name='Número do episódio'),
            preserve_default=False,
        ),
    ]
